server:
  port: 5000
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./app;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect


  h2:
    console:
      settings:
        web-allow-others: false # disable remote access
        trace: false  # prevent trace output
      #      path: /h2-console   # default path
      enabled: true
# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization
